[package]
name = "string_utils"
version = "0.1.0"
edition = "2021"
authors = ["Connor Prussin <connor@prussin.net>"]
description = "Random string utilities"
license = "MIT"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
